---
title: "Elissa Olivas"
author: "Elissa Olivas"
lang: "en"
excert_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true
show_excerpts: true
show_frame: true
show_sidebar: false

# Menu

navigation:
 -{file: "crochet.html", title:"Projects", icon: projects}
 -{file: "README.md", title: "About Me", icone: Home}
 
 plugins:
 - jekyll-feed
 ---

theme: jekyll-theme-architect