title: "Elissa Olivas"
author: "Elissa Olivas"
lang: "en"
excert_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true
show_excerpts: true
show_frame: true
show_sidebar: false

# Menu

navigation:
 -{file: "index.html", title:"Home", icon: home}
 -{file: "README.md", title: "About Me", icone: address-card}
 
 plugins:
 - jekyll-feed
 
