theme: jekyll-theme-slate

# Layout

show_social: true 
show_excerpts: true
show_frame: true
show_sidebar: false

# Menu

navigation:
 - {file: "index.html", title: Home, icon hoe}
 - {file: "README.md", title: About Me, icon: address-card}
